controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]

    wheel_separation: 0.30
    wheel_radius: 0.05

    publish_rate: 50.0
    use_stamped_vel: false

    odom_frame_id: odom
    base_frame_id: base_link

    enable_odom_tf: true
    use_sim_time: true
